name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build3-1:
    env:
      PROJECT_DIRECTORY: dotnet3.1
      SOLUTION_FILE: DependencyInjection.sln
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: $PROJECT_DIRECTORY
      run: dotnet restore $SOLUTION_FILE
    - name: Build
      working-directory: $PROJECT_DIRECTORY
      run: dotnet build --no-restore $SOLUTION_FILE
    - name: Test
      working-directory: $PROJECT_DIRECTORY
      run: dotnet test --no-build --verbosity normal $SOLUTION_FILE
