name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build3-1:
    env:
      PROJECT_DIRECTORY: ./dotnet3.1
      SOLUTION_FILE: DependencyInjection.sln
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $PROJECT_DIRECTORY

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: List files
      run: ls -la
    - name: List files in project folder
      run: ls -la
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
