name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build3-1:
    env:
      project-directory: ./dotnet31
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ project-directory }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ project-directory }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ project-directory }}
